# compatible with compose v2  only
name: calcs

services:
  calcs-db:
    container_name: dbcalcs
    image: postgres:16.2-alpine3.19
    env_file: .env-db
    ports:
      - "5433:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - calcs

  calcs-redis:
    container_name: rediscalcs
    image: redis:7.2.4-alpine
    ports:
      - "6380:6379"
    networks:
      - calcs

  calcs-api:
    container_name: backendcals
    image: jvrochadev/calcsbackend:0.1
    ports:
      - "6002:8000"
    env_file: .env
    volumes:
      - .:/app
    networks:
      - calcs
    depends_on:
      - calcs-db
      - calcs-redis

volumes:
  app: {}
  dbdata: {}

networks:
  calcs:
    driver: bridge
