version: '3.1'

services:
  calcs-db:
    container_name: dbcalcs
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${DATABASE_PORT}:5432"

  calcs-api:
    container_name: calcsbackend
    image: calcs-back-image:latest
    build: .
    ports:
      - "${PORT}:8000"
    depends_on:
      - calcs-db

    